### ISSUE TITLE
Review

### ISSUE THREAD

**Issue by Athesto** [rodrigozarate/simple_shell#17]
# Errores
- Aquí hay un problema de espaciados dentro del do-while-loop 
https://github.com/rodrigozarate/simple_shell/blob/83f12015f7a139fa0f2309cd1b26c1e9f597d8e6/main.c#L59

# Sugerencias
-  si ya existe una función (strlen), deberías usar un nombre derivado para evitar confusión como (`_strlen`)
https://github.com/rodrigozarate/simple_shell/blob/83f12015f7a139fa0f2309cd1b26c1e9f597d8e6/countstr.c#L15

- no deberías usar letras cortas para funciones simples.  razon (CleanCode, Chapter 2: Meaningful Names)
https://github.com/rodrigozarate/simple_shell/blob/83f12015f7a139fa0f2309cd1b26c1e9f597d8e6/countstr.c#L17

**Comment by rodrigozarate** [comment]
solved

simple_shell/main.c
Line 59 in 83f1201

**Comment by rodrigozarate** [comment]
Solved
simple_shell/countstr.c
Line 17 in 83f1201
Changed to i as is a counter in a for loop

Function and file renamed to _strlen
